import { Pager, HasState } from 'coreds/lib/types';
export { form } from './form';
export * from '../handler';
export declare function dropdown_msg(hs: HasState, mask: number): any;
export declare function lsearch_disabled(pager: Pager): boolean;
export declare function lsearch_input(pager: Pager, placeholder: string, fields: string[], fn?: Function, clazz?: string): any;
export declare function $pager<T>(pager: Pager, el: T): T;
export declare function pager_controls(pager: Pager): any;
export declare function pager_controls_nav(pager: Pager): any;
export declare function pager_msg(pager: Pager): any;
export declare function icon_timeago(pojo: any, wrapper_class?: string): any;
export declare function icon_update_ts(pojo: any, fk: string, wrapper_class?: string): any;
export declare function icon_toggle(pojo: any, fk: string, bit: number, icon_class: string, cb: Function, name?: string, wrapper_class?: string): any;
export declare function icon_toggle_dd(pojo: any, fk: string, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function icon_action(pojo: any, bit: number, icon_class: string, cb: Function, name?: string, wrapper_class?: string): any;
export declare function icon_action_dd(pojo: any, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function list_class(pager: Pager): "ui small divided selection list loading loading-lg" | "ui small divided selection list";
export declare function $item<T>(pojo: any, el: T): T;
export declare function item_class(pojo: any): "d-none" | "item" | "item active";
export declare function item_msg(pojo: any): any;
export declare function item_msg_dd(pojo: any): any;
export declare function item_timeago(pojo: any): any;
export declare function item_update_ts(pojo: any, fk: string): any;
export declare function item_toggle(pojo: any, fk: string, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function item_toggle_dd(pojo: any, fk: string, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function item_action(pojo: any, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function item_action_dd(pojo: any, bit: number, icon_class: string, cb: Function, name?: string): any;
export declare function item_remove32(pojo: any, cb: Function): any;
export declare function item_remove32_dd(pojo: any, cb: Function): any;
export declare function item_detail(pojo: any, detail_id: string): any;
