export { form } from './form';
export { qform } from './qform';
export declare function dropdown_msg(hs: string, mask: number): string;
export declare function lsearch_attrs(fk: string): string;
export declare const suggest_controls: string;
export declare const pager_controls: string;
export declare const pager_msg: string;
export declare function icon_timeago(wrapper_class?: string): string;
export declare function icon_update_ts(fk: string, wrapper_class?: string): string;
export declare function icon_toggle(fk: string, bit: number, icon_class: string, name?: string, wrapper_class?: string): string;
export declare function icon_toggle_dd(fk: string, bit: number, icon_class: string, name?: string): string;
export declare function icon_action(bit: number, icon_class: string, name?: string, wrapper_class?: string): string;
export declare function icon_action_dd(bit: number, icon_class: string, name?: string): string;
export declare const item_attrs: string;
export declare const item_msg: string;
export declare const item_msg_dd: string;
export declare const item_timeago: string;
export declare function item_update_ts(fk: string): string;
export declare function item_toggle(fk: string, bit: number, icon_class: string, name?: string): string;
export declare function item_toggle_dd(fk: string, bit: number, icon_class: string, name?: string): string;
export declare function item_action(bit: number, icon_class: string, name?: string): string;
export declare function item_action_dd(bit: number, icon_class: string, name?: string): string;
export declare const item_remove32: string;
export declare const item_remove32_dd: string;
export declare function item_detail(detail_id: string): string;
