export declare function $hide0_on_esc(e: any): void;
export declare function $hide1_on_esc(e: any): void;
export declare function $clearMsg(this: any, e: any): void;
export declare function $toggle0(e: any): void;
export declare function $toggle1(e: any): void;
export declare function $toggle2(e: any): void;
export declare function $toggle3(e: any): void;
export declare function $itoggle0(e: any): void;
export declare function $itoggle1(e: any): void;
export declare function $itoggle2(e: any): void;
export declare function $itoggle3(e: any): void;
